<?xml version="1.0" encoding="utf-8"?>
<Course>
<Computer_Science>
<Student_name>Nihal</Student_name>
<Class_name>TYBCS</Class_name>
<percentage>80</percentage>
</Computer_Science>
<Computer_Science>
<Student_name>Alim</Student_name>
<Class_name>TYBCS</Class_name>
<percentage>65</percentage>
</Computer_Science>
<Computer_Science>
<Student_name>Tushar</Student_name>
<Class_name>TYBCS</Class_name>
<percentage>90</percentage>
</Computer_Science>
<Computer_Science>
<Student_name>Yasin</Student_name>
<Class_name>TYBCS</Class_name>
<percentage>85</percentage>
</Computer_Science>
<Computer_Science>
<Student_name>Atharv</Student_name>
<Class_name>TYBCS</Class_name>
<percentage>88</percentage>
</Computer_Science>
</Course>
